http://localhost:4000/
###
http://localhost:4002/status
###
http://localhost:4001/balance/6308e20ddaeae91a48a7e07791d5dabb814bae4a1e44595b0253c6051dc1c260cc6d0747370172c0db48aec400f0dbf7badbeada4f585ecd7ef5115e1dddd433
###
http://localhost:4001/balance/c0c169399013db563e5b6a07cb207df7bbe782b230bbf6c632f6faf83e618af73ca28a42cdf328400bc19ef47f5a6b10baaa54df719b5356d3eb65453a36c0a5?total=true
###
http://localhost:3000/blocks
###
http://localhost:4000/wallet
###
POST http://localhost:4001/blocks
###
POST http://localhost:4002/transactions

{
    "to":"kkk",
    "amount":10,
    "inputData":"any string"
}
###
POST http://localhost:4001/stake
###
POST http://localhost:4001/unstake
### 
http://localhost:4001/mempool
###
http://localhost:4001/peer
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "3000"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4001"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4002"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4003"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4004"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4005"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4006"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4007"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4008"
}
###
POST http://localhost:4000/peer

{
    "address": "127.0.0.1",
    "port": "4009"
}
